application.name: spring-graphql-demo
spring.graphql.graphiql.enabled: true
spring.graphql.schema.fileExtensions: .graphql, .graphqls
# the below property is for CORS
spring.mvc.dispatch-options-request: true